import React from 'react';
import {
  Modal,
  View,
  ScrollView,
  TouchableOpacity,
  StyleSheet,
  Platform,
} from 'react-native';
import { ThemedText } from '@/components/ThemedText';
import { useThemeColors } from '@/hooks/use-theme-colors';
import { Colors, Spacing } from '@/constants/theme';

export type LegalType = 'terms' | 'privacy';

interface Props {
  visible: boolean;
  type: LegalType;
  onClose: () => void;
  /** If provided, shows an "Accept" button and calls this when tapped */
  onAccept?: () => void;
}

// ─── Content ──────────────────────────────────────────────────────────────────

const TERMS_SECTIONS = [
  {
    heading: '1. Acceptance of Terms',
    body: 'By creating an account and using FocusFlow ("the App"), you agree to be bound by these Terms and Conditions. If you do not agree, please do not use the App.',
  },
  {
    heading: '2. Description of Service',
    body: 'FocusFlow is a productivity application that implements the Pomodoro Technique to help users manage focus sessions, tasks, and breaks. The App may be updated, modified, or discontinued at any time without prior notice.',
  },
  {
    heading: '3. User Accounts',
    body: 'You are responsible for maintaining the confidentiality of your account credentials. You agree to provide accurate information during registration and to notify us immediately of any unauthorized use of your account.',
  },
  {
    heading: '4. Acceptable Use',
    body: 'You agree not to misuse the App, attempt to gain unauthorized access to any part of the service, transmit harmful or unlawful content, or interfere with the proper functioning of the App.',
  },
  {
    heading: '5. Data and Analytics',
    body: 'The App collects session history, task data, and usage analytics to provide and improve the service. You may reset or delete this data at any time from your profile settings.',
  },
  {
    heading: '6. Intellectual Property',
    body: 'All content, trademarks, and intellectual property within the App are owned by FocusFlow or its licensors. You may not reproduce, distribute, or create derivative works without explicit written permission.',
  },
  {
    heading: '7. Disclaimer of Warranties',
    body: 'The App is provided "as is" without warranties of any kind, express or implied. We do not guarantee uninterrupted or error-free operation of the service.',
  },
  {
    heading: '8. Limitation of Liability',
    body: 'To the maximum extent permitted by law, FocusFlow shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the App.',
  },
  {
    heading: '9. Changes to Terms',
    body: 'We reserve the right to modify these Terms at any time. Continued use of the App after changes constitutes acceptance of the updated Terms.',
  },
  {
    heading: '10. Contact',
    body: 'For questions about these Terms, please contact us through the App or at our official support channels.',
  },
];

const PRIVACY_SECTIONS = [
  {
    heading: '1. Information We Collect',
    body: 'We collect information you provide directly (name, email address) and data generated by your use of the App (Pomodoro sessions, tasks, schedules, and usage patterns).',
  },
  {
    heading: '2. How We Use Your Information',
    body: 'Your data is used to provide and improve the App, personalize your experience, generate productivity analytics, and communicate important service updates.',
  },
  {
    heading: '3. Data Storage',
    body: 'Your data is stored securely using Supabase infrastructure with industry-standard encryption at rest and in transit. We do not sell your personal data to third parties.',
  },
  {
    heading: '4. Session Data',
    body: 'Pomodoro session history, task data, and generated schedules are stored to power your analytics dashboard. You can permanently delete all this data at any time via Profile → Danger Zone → Reset Account Data.',
  },
  {
    heading: '5. Authentication',
    body: 'We use secure token-based authentication. Passwords are hashed and never stored in plain text. You can invalidate all active sessions at any time.',
  },
  {
    heading: '6. Third-Party Services',
    body: 'The App uses Supabase for backend services and Expo for the mobile runtime. These services have their own privacy policies which govern their data handling.',
  },
  {
    heading: '7. Your Rights',
    body: 'You have the right to access, correct, or delete your personal data at any time. You may also request a copy of your data or withdraw consent by deleting your account.',
  },
  {
    heading: '8. Cookies and Local Storage',
    body: 'The App uses local storage to persist your authentication session and preferences. No third-party tracking cookies are used.',
  },
  {
    heading: '9. Children\'s Privacy',
    body: 'The App is not directed at children under 13. We do not knowingly collect personal information from children under 13.',
  },
  {
    heading: '10. Changes to This Policy',
    body: 'We may update this Privacy Policy periodically. We will notify you of significant changes through the App. Continued use after changes constitutes acceptance.',
  },
];

// ─── Component ────────────────────────────────────────────────────────────────

export function LegalModal({ visible, type, onClose, onAccept }: Props) {
  const colors = useThemeColors();
  const isTerms = type === 'terms';
  const sections = isTerms ? TERMS_SECTIONS : PRIVACY_SECTIONS;
  const title = isTerms ? 'Terms & Conditions' : 'Privacy Policy';
  const lastUpdated = 'Last updated: May 2026';

  const s = styles(colors);

  return (
    <Modal
      visible={visible}
      transparent
      animationType="slide"
      onRequestClose={onClose}
      statusBarTranslucent
    >
      <View style={s.overlay}>
        <View style={s.sheet}>
          {/* Header */}
          <View style={s.header}>
            <View>
              <ThemedText variant="headlineSmall" color={colors.onSurface}>{title}</ThemedText>
              <ThemedText variant="labelSmall" color={colors.onSurfaceVariant}>{lastUpdated}</ThemedText>
            </View>
            <TouchableOpacity style={s.closeButton} onPress={onClose} hitSlop={{ top: 8, bottom: 8, left: 8, right: 8 }}>
              <ThemedText variant="titleMedium" color={colors.onSurfaceVariant}>✕</ThemedText>
            </TouchableOpacity>
          </View>

          {/* Divider */}
          <View style={s.divider} />

          {/* Scrollable content */}
          <ScrollView
            style={s.scroll}
            contentContainerStyle={s.scrollContent}
            showsVerticalScrollIndicator={false}
          >
            {sections.map((section) => (
              <View key={section.heading} style={s.section}>
                <ThemedText variant="titleSmall" color={colors.onSurface} style={s.sectionHeading}>
                  {section.heading}
                </ThemedText>
                <ThemedText variant="bodyMedium" color={colors.onSurfaceVariant} style={s.sectionBody}>
                  {section.body}
                </ThemedText>
              </View>
            ))}
          </ScrollView>

          {/* Footer */}
          <View style={s.footer}>
            {onAccept ? (
              <View style={s.footerRow}>
                <TouchableOpacity style={s.declineButton} onPress={onClose}>
                  <ThemedText variant="labelLarge" color={colors.onSurfaceVariant}>Decline</ThemedText>
                </TouchableOpacity>
                <TouchableOpacity style={s.acceptButton} onPress={() => { onAccept(); onClose(); }}>
                  <ThemedText variant="labelLarge" color="#fff">Accept</ThemedText>
                </TouchableOpacity>
              </View>
            ) : (
              <TouchableOpacity style={s.closeFullButton} onPress={onClose}>
                <ThemedText variant="labelLarge" color={colors.onSurface}>Close</ThemedText>
              </TouchableOpacity>
            )}
          </View>
        </View>
      </View>
    </Modal>
  );
}

const styles = (colors: ReturnType<typeof useThemeColors>) =>
  StyleSheet.create({
    overlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.6)',
      justifyContent: 'flex-end',
    },
    sheet: {
      backgroundColor: colors.surfaceContainer,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      maxHeight: '88%',
      paddingBottom: Platform.OS === 'ios' ? 34 : 0,
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      paddingHorizontal: Spacing.lg,
      paddingTop: Spacing.lg,
      paddingBottom: Spacing.md,
    },
    closeButton: {
      padding: Spacing.xs,
    },
    divider: {
      height: 1,
      backgroundColor: colors.outlineVariant,
      marginHorizontal: Spacing.lg,
    },
    scroll: {
      flex: 1,
    },
    scrollContent: {
      paddingHorizontal: Spacing.lg,
      paddingTop: Spacing.md,
      paddingBottom: Spacing.lg,
      gap: Spacing.lg,
    },
    section: {
      gap: Spacing.xs,
    },
    sectionHeading: {
      fontWeight: '600',
    },
    sectionBody: {
      lineHeight: 22,
    },
    footer: {
      paddingHorizontal: Spacing.lg,
      paddingVertical: Spacing.md,
      borderTopWidth: 1,
      borderTopColor: colors.outlineVariant,
    },
    footerRow: {
      flexDirection: 'row',
      gap: Spacing.md,
    },
    declineButton: {
      flex: 1,
      paddingVertical: 14,
      borderRadius: 12,
      backgroundColor: colors.surfaceContainerLow,
      alignItems: 'center',
    },
    acceptButton: {
      flex: 1,
      paddingVertical: 14,
      borderRadius: 12,
      backgroundColor: Colors.primary,
      alignItems: 'center',
    },
    closeFullButton: {
      paddingVertical: 14,
      borderRadius: 12,
      backgroundColor: colors.surfaceContainerLow,
      alignItems: 'center',
    },
  });
